apiVersion: v1
kind: Pod
metadata:
  name: robot-b
  labels:
    app: robot-b
spec:
  containers:
  - name: agent
    image: swarm-agent:latest
    imagePullPolicy: Never
    env:
    - name: RMW_IMPLEMENTATION
      value: rmw_zenoh_cpp
    - name: ZENOH_CONFIG_OVERRIDE
      value: 'mode="client";connect/endpoints=["tcp/zenoh-router:7447"]'
    args: ["ros2", "run", "swarm_agent", "agent_node", "--ros-args", "-r", "__node:=robot_b", "-p", "robot_id:=robot_b", "-p", "start_x:=10.0", "-p", "start_y:=10.0"]
